"""
visual_generator.py — Intelligent Visual Asset Collection

Collects images for each scene from the Pexels stock photo API using
semantically-targeted, multi-query search with candidate ranking.

Pipeline per scene:
  1. Get visual_queries from the script (generated by Gemini) or derive
     fallback queries from the narration + visual_prompt.
  2. For each query, search Pexels and collect multiple candidate results.
  3. Rank candidates by relevance to the scene narration using keyword
     overlap scoring.
  4. Select the highest-scoring unused candidate.
  5. Download and crop to 16:9 YouTube dimensions.
  6. Track used Pexels photo IDs to prevent duplicate visuals across scenes.

Falls back to colored placeholder images when the API key is missing or
all searches fail.

Pexels API docs: https://www.pexels.com/api/documentation/
"""

import json
import random
import re
import sys
from pathlib import Path

import requests
from PIL import Image, ImageDraw, ImageFont

from scripts.config import ASSETS_DIR, get_pexels_api_key

# ---------------------------------------------------------------------------
# Pexels API configuration
# ---------------------------------------------------------------------------
PEXELS_SEARCH_URL = "https://api.pexels.com/v1/search"

# Target image dimensions (YouTube 16:9)
IMAGE_WIDTH = 1280
IMAGE_HEIGHT = 720

# How many Pexels results to request per query (more = better candidate pool)
PEXELS_PER_PAGE = 15

# Maximum candidates to collect per query before ranking
MAX_CANDIDATES_PER_QUERY = 5

# ---------------------------------------------------------------------------
# Placeholder color palette (fallback)
# ---------------------------------------------------------------------------
SCENE_COLORS = [
    (41, 98, 255),    # Vivid blue
    (0, 200, 83),     # Green
    (255, 109, 0),    # Orange
    (156, 39, 176),   # Purple
    (0, 184, 212),    # Cyan
    (255, 61, 0),     # Red-orange
    (76, 175, 80),    # Medium green
    (63, 81, 181),    # Indigo
    (233, 30, 99),    # Pink
    (121, 85, 72),    # Brown
    (0, 150, 136),    # Teal
    (255, 193, 7),    # Amber
]


# ---------------------------------------------------------------------------
# Noise / stop word sets for query generation and relevance scoring
# ---------------------------------------------------------------------------
_CINEMATIC_NOISE = {
    "close-up", "closeup", "wide", "shot", "slow", "zoom", "pan",
    "dolly", "tracking", "aerial", "overhead", "cinematic", "lighting",
    "dramatic", "blue", "warm", "cool", "soft", "bokeh", "depth",
    "field", "focus", "blur", "exposure", "frame", "angle", "perspective",
    "reveal", "cut", "transition", "establishing", "handheld", "steadicam",
    "timelapse", "time-lapse", "slo-mo", "slow-motion", "motion",
    "camera", "lens", "aperture", "shutter", "iso", "raw", "footage",
    "b-roll", "broll", "stock", "4k", "hd", "1080p",
    "showing", "displaying", "featuring", "depicting", "illustrating",
    "representing", "demonstrating", "highlighting",
}

_STOP_WORDS = {
    "a", "an", "the", "of", "for", "in", "on", "with", "and", "or",
    "at", "to", "by", "from", "up", "into", "over", "after", "as",
    "is", "are", "was", "were", "be", "been", "that", "this", "their",
    "its", "it", "about", "where", "when", "which", "who", "not",
    "can", "will", "would", "could", "should", "have", "has", "had",
    "do", "does", "did", "but", "you", "your", "they", "we", "our",
    "how", "what", "why", "just", "also", "even", "more", "most",
    "very", "being", "than", "now", "then",
}

# Generic stock photo terms that are penalised during ranking because
# they produce semantically weak results on Pexels
_GENERIC_PENALTY_TERMS = {
    "person", "people", "man", "woman", "laptop", "computer", "office",
    "desk", "table", "room", "building", "city", "nature", "sky",
    "abstract", "background", "concept", "technology", "business",
}


# ---------------------------------------------------------------------------
# Query generation
# ---------------------------------------------------------------------------
def _extract_keywords(text: str, max_words: int = 6) -> list[str]:
    """Extract meaningful keywords from text, filtering noise."""
    all_noise = _CINEMATIC_NOISE | _STOP_WORDS
    cleaned = re.sub(r"[^\w\s-]", " ", text.lower())
    words = cleaned.split()
    keywords = [
        w for w in words
        if w not in all_noise and len(w) >= 3 and not w.isdigit()
    ]
    return keywords[:max_words]


def _generate_fallback_queries(
    narration: str,
    visual_prompt: str,
    topic: str = "",
) -> list[str]:
    """
    Derive 2–3 Pexels search queries from scene text when Gemini
    did not provide visual_queries.

    Returns queries ordered from most specific to broadest.
    """
    queries = []

    # Specific: key nouns from the narration
    narr_kw = _extract_keywords(narration, max_words=5)
    if len(narr_kw) >= 2:
        queries.append(" ".join(narr_kw[:5]))

    # Contextual: keywords from the visual prompt (strip cinematic terms)
    vp_kw = _extract_keywords(visual_prompt, max_words=5)
    if vp_kw:
        vp_query = " ".join(vp_kw[:5])
        if vp_query not in queries:
            queries.append(vp_query)

    # Broader: combine topic with narration essence
    if topic:
        topic_kw = _extract_keywords(topic, max_words=3)
        if narr_kw and topic_kw:
            broad = " ".join(topic_kw[:2] + narr_kw[:2])
            if broad not in queries:
                queries.append(broad)

    # Ensure at least one query
    if not queries:
        fallback = _extract_keywords(visual_prompt or narration, max_words=4)
        queries.append(" ".join(fallback) if fallback else "professional workplace")

    return queries[:3]


# ---------------------------------------------------------------------------
# Pexels search — returns multiple candidates
# ---------------------------------------------------------------------------
def _search_pexels_candidates(
    query: str,
    api_key: str,
    exclude_ids: set[int] | None = None,
    max_candidates: int = MAX_CANDIDATES_PER_QUERY,
    aspect_ratio: str = "16:9",
) -> list[dict]:
    """
    Search Pexels and return multiple candidate photos (not just the first).

    Each candidate is a dict:
        {
            "photo_id": int,
            "url": str,           # download URL (large2x or large)
            "alt": str,           # Pexels alt text (describes the photo)
            "photographer": str,
            "avg_color": str,
        }

    Candidates already in exclude_ids are skipped.
    """
    if exclude_ids is None:
        exclude_ids = set()

    headers = {"Authorization": api_key}
    orientation = "portrait" if aspect_ratio == "9:16" else "landscape"
    params = {
        "query": query,
        "per_page": PEXELS_PER_PAGE,
        "page": 1,
        "orientation": orientation,
        "size": "large",
    }

    try:
        response = requests.get(
            PEXELS_SEARCH_URL,
            headers=headers,
            params=params,
            timeout=10,
        )
        response.raise_for_status()
    except Exception as e:
        print(f"  [WARN] Pexels API error for query '{query}': {e}")
        return []

    data = response.json()
    photos = data.get("photos", [])

    candidates = []
    for photo in photos:
        photo_id = photo.get("id")
        if photo_id in exclude_ids:
            continue

        src = photo.get("src", {})
        if aspect_ratio == "9:16":
            url = src.get("portrait") or src.get("original") or src.get("large")
        else:
            url = src.get("landscape") or src.get("large2x") or src.get("large")
            
        if not url:
            continue

        candidates.append({
            "photo_id": photo_id,
            "url": url,
            "alt": photo.get("alt", ""),
            "photographer": photo.get("photographer", ""),
            "avg_color": photo.get("avg_color", ""),
        })

        if len(candidates) >= max_candidates:
            break

    return candidates


# ---------------------------------------------------------------------------
# Candidate ranking by narration relevance
# ---------------------------------------------------------------------------
def _rank_candidates(
    candidates: list[dict],
    narration: str,
    visual_prompt: str,
    query_used: str,
) -> list[dict]:
    """
    Score and sort candidates by relevance to the scene narration.

    Scoring heuristic (no ML dependencies):
    - +2 for each narration keyword found in the Pexels alt text
    - +1 for each visual_prompt keyword found in alt text
    - +1 for each query keyword found in alt text
    - -1 for each generic stock term in alt text (penalty for semantic weakness)
    - Bonus +3 if the alt text contains a multi-word narration phrase (2+ words)

    Returns candidates sorted by score descending (best first).
    """
    narr_keywords = set(_extract_keywords(narration, max_words=10))
    vp_keywords = set(_extract_keywords(visual_prompt, max_words=8))
    query_keywords = set(query_used.lower().split())

    scored = []
    for cand in candidates:
        alt_lower = cand["alt"].lower()
        alt_words = set(re.sub(r"[^\w\s]", " ", alt_lower).split())
        score = 0

        # Narration keyword matches (highest weight)
        narr_matches = narr_keywords & alt_words
        score += len(narr_matches) * 2

        # Visual prompt keyword matches
        vp_matches = vp_keywords & alt_words
        score += len(vp_matches) * 1

        # Query keyword matches
        q_matches = query_keywords & alt_words
        score += len(q_matches) * 1

        # Phrase matching bonus — check if 2-word narration phrases appear in alt
        narr_kw_list = list(narr_keywords)
        for i in range(len(narr_kw_list) - 1):
            phrase = f"{narr_kw_list[i]} {narr_kw_list[i+1]}"
            if phrase in alt_lower:
                score += 3

        # Penalty for overly generic stock terms
        generic_in_alt = _GENERIC_PENALTY_TERMS & alt_words
        # Only penalise when most of the alt text is generic
        if len(generic_in_alt) > 0 and len(narr_matches) == 0:
            score -= len(generic_in_alt)

        cand["_relevance_score"] = score
        scored.append(cand)

    # Sort by score descending, then by photo_id for determinism
    scored.sort(key=lambda c: (-c["_relevance_score"], c["photo_id"]))
    return scored


# ---------------------------------------------------------------------------
# Image download & processing
# ---------------------------------------------------------------------------
def _download_image(url: str, save_path: str) -> bool:
    """
    Download an image from a URL and save it as JPEG.

    Returns True on success, False on failure.
    """
    try:
        response = requests.get(url, timeout=30, stream=True)
        response.raise_for_status()

        # Open with Pillow to resize to exact YouTube dimensions and re-save
        from io import BytesIO
        img = Image.open(BytesIO(response.content)).convert("RGB")

        # Crop to 16:9 aspect ratio then resize
        target_ratio = IMAGE_WIDTH / IMAGE_HEIGHT
        w, h = img.size
        current_ratio = w / h

        if current_ratio > target_ratio:
            # Image is wider -- crop the sides
            new_w = int(h * target_ratio)
            left = (w - new_w) // 2
            img = img.crop((left, 0, left + new_w, h))
        else:
            # Image is taller -- crop top and bottom
            new_h = int(w / target_ratio)
            top = (h - new_h) // 2
            img = img.crop((0, top, w, top + new_h))

        img = img.resize((IMAGE_WIDTH, IMAGE_HEIGHT), Image.LANCZOS)
        img.save(save_path, "JPEG", quality=90)
        return True

    except Exception as e:
        print(f"  [WARN] Failed to download image: {e}")
        return False


def _reuse_existing_image(
    source_path: str,
    save_path: str,
) -> bool:
    """
    Create a visually varied copy of an existing image.

    Applies a slight crop offset to make the reused image look different
    from the original without requiring another API call.

    Returns True on success, False on failure.
    """
    try:
        img = Image.open(source_path).convert("RGB")
        w, h = img.size

        # Apply a random crop offset (5-10% from a random edge)
        offset_x = random.randint(int(w * 0.03), int(w * 0.10))
        offset_y = random.randint(int(h * 0.03), int(h * 0.10))
        side = random.choice(["left", "right", "top", "bottom"])

        if side == "left":
            img = img.crop((offset_x, 0, w, h))
        elif side == "right":
            img = img.crop((0, 0, w - offset_x, h))
        elif side == "top":
            img = img.crop((0, offset_y, w, h))
        else:
            img = img.crop((0, 0, w, h - offset_y))

        img = img.resize((IMAGE_WIDTH, IMAGE_HEIGHT), Image.LANCZOS)
        img.save(save_path, "JPEG", quality=90)
        return True
    except Exception as e:
        print(f"  [WARN] Failed to reuse image: {e}")
        return False


def _create_placeholder_image(
    path: str,
    scene_number: int,
    visual_prompt: str,
    aspect_ratio: str = "16:9",
):
    """
    Create a colored placeholder image with scene info text.

    Used as fallback when Pexels is unavailable.
    """
    bg_color = SCENE_COLORS[(scene_number - 1) % len(SCENE_COLORS)]
    dark_color = tuple(max(0, c - 40) for c in bg_color)
    
    img_w, img_h = (1080, 1920) if aspect_ratio == "9:16" else (1920, 1080)

    img = Image.new("RGB", (img_w, img_h), bg_color)
    draw = ImageDraw.Draw(img)

    rect_top = img_h * 2 // 3
    draw.rectangle([0, rect_top, img_w, img_h], fill=dark_color)

    try:
        font_large = ImageFont.truetype("arial.ttf", 48)
        font_small = ImageFont.truetype("arial.ttf", 24)
    except (IOError, OSError):
        font_large = ImageFont.load_default()
        font_small = font_large

    label = f"Scene {scene_number}"
    bbox = draw.textbbox((0, 0), label, font=font_large)
    text_width = bbox[2] - bbox[0]
    draw.text(
        ((img_w - text_width) // 2, img_h // 3),
        label,
        fill="white",
        font=font_large,
    )

    prompt_display = visual_prompt[:80] + "..." if len(visual_prompt) > 80 else visual_prompt
    bbox2 = draw.textbbox((0, 0), prompt_display, font=font_small)
    text_width2 = bbox2[2] - bbox2[0]
    draw.text(
        ((img_w - text_width2) // 2, rect_top + 30),
        prompt_display,
        fill="white",
        font=font_small,
    )

    img.save(path, "JPEG", quality=90)


# ---------------------------------------------------------------------------
# Main visual collection — multi-query, ranked selection
# ---------------------------------------------------------------------------
def collect_visuals(
    script: dict,
    output_dir: str = None,
    tone: str = "",
    style: str = "",
    aspect_ratio: str = "16:9",
) -> list[str]:
    """
    Collect visual assets for each scene from Pexels using intelligent
    multi-query search with candidate ranking.

    For each scene:
    1. Use visual_queries from the script (generated by Gemini) if available,
       otherwise derive fallback queries from narration + visual_prompt.
    2. For each query, search Pexels and collect multiple candidates.
    3. Rank all candidates by relevance to the scene narration.
    4. Select the highest-scoring candidate not already used.
    5. Download and save.

    Args:
        script:     The script dict from script_generator.generate_script().
        output_dir: Directory to save images. Defaults to assets/.
        tone:       Script tone (influences query style in fallbacks).
        style:      Video style (influences query style in fallbacks).

    Returns:
        A list of file paths to the collected images, one per scene.
    """
    if output_dir is None:
        output_dir = str(ASSETS_DIR)

    out_path = Path(output_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    # Try to get Pexels API key -- if missing, all scenes use placeholders
    try:
        api_key = get_pexels_api_key()
        use_pexels = True
    except ValueError:
        print("  [INFO] PEXELS_API_KEY not configured, using placeholder images")
        use_pexels = False

    image_files = []
    used_photo_ids: set[int] = set()         # Track Pexels photo IDs for deduplication
    downloaded_paths: list[str] = []          # Track successfully downloaded files for reuse

    scenes = script.get("scenes", [])
    total = len(scenes)
    topic = script.get("topic", "")

    for scene in scenes:
        scene_num = scene["scene_number"]
        narration = scene.get("narration", "")
        visual_prompt = scene.get("visual_prompt", f"Scene {scene_num}")

        filename = f"scene_{scene_num:02d}_visual.jpg"
        filepath = str(out_path / filename)

        downloaded = False

        if use_pexels:
            # --- Step 1: Get search queries ---
            queries = scene.get("visual_queries", [])
            if not queries or not isinstance(queries, list):
                # Derive fallback queries from narration + visual_prompt
                queries = _generate_fallback_queries(narration, visual_prompt, topic)
                print(f"  [INFO] Scene {scene_num}: generated fallback queries: {queries}")
            else:
                print(f"  [INFO] Scene {scene_num}: using Gemini queries: {queries}")

            # --- Step 2–4: Multi-query search, collect candidates, rank ---
            all_candidates = []
            queries_tried = []

            try:
                for q_idx, query in enumerate(queries):
                    candidates = _search_pexels_candidates(
                        query, api_key, used_photo_ids, max_candidates=MAX_CANDIDATES_PER_QUERY, aspect_ratio=aspect_ratio
                    )
                    queries_tried.append(query)

                    if candidates:
                        # Tag candidates with the query that found them
                        for c in candidates:
                            c["_source_query"] = query
                        all_candidates.extend(candidates)
                        print(f"    Query {q_idx+1} '{query}': {len(candidates)} candidates")
                    else:
                        print(f"    Query {q_idx+1} '{query}': no results")

                    # If we have enough good candidates from specific queries,
                    # skip the broader fallback query
                    if len(all_candidates) >= MAX_CANDIDATES_PER_QUERY * 2:
                        break

                # --- Step 5: Rank and select ---
                if all_candidates:
                    # Deduplicate candidates by photo_id
                    seen_ids = set()
                    unique_candidates = []
                    for c in all_candidates:
                        if c["photo_id"] not in seen_ids:
                            seen_ids.add(c["photo_id"])
                            unique_candidates.append(c)

                    ranked = _rank_candidates(
                        unique_candidates, narration, visual_prompt,
                        query_used=" ".join(queries_tried),
                    )

                    # Pick the best unused candidate
                    for best in ranked:
                        if best["photo_id"] not in used_photo_ids:
                            downloaded = _download_image(best["url"], filepath)
                            if downloaded:
                                used_photo_ids.add(best["photo_id"])
                                downloaded_paths.append(filepath)
                                score = best.get("_relevance_score", 0)
                                alt_preview = best["alt"][:60] if best["alt"] else "no alt"
                                print(
                                    f"  [OK] Scene {scene_num}/{total}: {filename} "
                                    f"(score={score}, alt='{alt_preview}')"
                                )
                                break

                # If no suitable candidate found, try reusing
                if not downloaded and downloaded_paths:
                    source = downloaded_paths[scene_num % len(downloaded_paths)]
                    downloaded = _reuse_existing_image(source, filepath)
                    if downloaded:
                        print(f"  [OK] Scene {scene_num}/{total}: {filename} (reused with variation)")

            except Exception as e:
                print(f"  [WARN] Pexels fetch failed for scene {scene_num}: {e}")
                # Try reusing existing image before falling to placeholder
                if downloaded_paths:
                    source = downloaded_paths[scene_num % len(downloaded_paths)]
                    downloaded = _reuse_existing_image(source, filepath)
                    if downloaded:
                        print(f"  [OK] Scene {scene_num}/{total}: {filename} (reused after error)")

        if not downloaded:
            # Fallback: colored placeholder
            _create_placeholder_image(filepath, scene_num, visual_prompt, aspect_ratio=aspect_ratio)
            print(f"  [OK] Scene {scene_num}/{total}: {filename} (placeholder)")

        image_files.append(filepath)

    return image_files


# ---------------------------------------------------------------------------
# CLI entry point -- allows calling from n8n via:
#   python -m scripts.visual_generator --script-file assets/script.json
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Collect visuals for scenes")
    parser.add_argument(
        "--script-file",
        type=str,
        required=True,
        help="Path to script JSON file",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default=None,
        help="Directory to save image files",
    )
    parser.add_argument(
        "--tone",
        type=str,
        default="",
        help="Script tone for query generation",
    )
    parser.add_argument(
        "--style",
        type=str,
        default="",
        help="Video style for query generation",
    )
    args = parser.parse_args()

    with open(args.script_file, "r", encoding="utf-8") as f:
        script_data = json.load(f)

    files = collect_visuals(script_data, args.output_dir, args.tone, args.style)
    print(json.dumps({"image_files": files}, indent=2))
